name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build-Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --configuration Release --no-restore -o deploy

      - name: Copy via ssh
        uses: garygrossgarten/github-action-scp@v0.8.0
        with:
          local: /home/runner/work/thelazzoro/thelazzoro/src/deploy/
          host: ${{ secrets.SERVER_HOSTNAME }}
          remote: ${{ secrets.SERVER_REMOTE_DIR }}
          username: ${{ secrets.SERVER_USERNAME }}
          passphrase: ${{ secrets.SERVER_PASSWORD }}
          privateKey: ${{ secrets.KEY }}