name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build-Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --configuration Release --no-restore -o deploy

      - name: Copy via ssh
        uses: appleboy/scp-action@v0.1.4
        with:
          source: /home/runner/work/Exam-Security-WebApp-CSharp/Exam-Security-WebApp-CSharp/deploy/
          host: ${{ secrets.SERVER_HOSTNAME }}
          target: ${{ secrets.SERVER_REMOTE_DIR }}
          username: ${{ secrets.SERVER_USERNAME }}
          passphrase: ${{ secrets.SERVER_PASSWORD }}
          key: ${{ secrets.KEY }}
      
      - name: Start Server (SSH command)
        uses: appleboy/ssh-action@v0.1.10
        with:
          command: sudo dotnet /home/runner/work/Exam-Security-WebApp-CSharp/Exam-Security-WebApp-CSharp/deploy/WebApp.dll
          host: ${{ secrets.SERVER_HOSTNAME }}
          username: ${{ secrets.SERVER_USERNAME }}
          passphrase: ${{ secrets.SERVER_PASSWORD }}
          key: ${{ secrets.KEY }}